"""rename video_screenshot to character_screenshot

Revision ID: 0d048e1cbb51
Revises: a2ceb92d3ea0
Create Date: 2026-02-27 16:34:36.688266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d048e1cbb51'
down_revision: Union[str, Sequence[str], None] = 'a2ceb92d3ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
